// Small repositories of the Python web frameworks (business-flows/38), written
// into a temporary directory by `tests/frameworks-python-web.test.ts`.

const lines = (...rows: string[]): string => `${rows.join("\n")}\n`;

/** Django with Celery: `urls.py` with `include` and a class-based view, signals, a management command, tasks and `beat_schedule`. */
export const DJANGO: Record<string, string> = {
  "keylang.json": JSON.stringify({ languages: ["python"], module: "file", layers: { shop: ["shop/**", "manage.py"], orders: ["orders/**"], notify: ["notify/**"] } }),
  "requirements.txt": lines("Django>=4.2", "celery[redis]>=5"),
  "manage.py": lines(
    "import os",
    "import sys",
    "",
    "",
    "def main():",
    '    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "shop.settings")',
    "    from django.core.management import execute_from_command_line",
    "    execute_from_command_line(sys.argv)",
    "",
    "",
    'if __name__ == "__main__":',
    "    main()",
  ),
  "shop/__init__.py": "",
  "shop/settings.py": lines(
    "from celery.schedules import crontab",
    "",
    'ROOT_URLCONF = "shop.urls"',
    "CELERY_BEAT_SCHEDULE = {",
    '    "cleanup-stale": {"task": "orders.tasks.cleanup", "schedule": crontab(minute=0, hour="*/3")},',
    '    "nightly": {"task": "orders.tasks.missing", "schedule": crontab(minute=30, hour=2)},',
    "}",
  ),
  "shop/celery.py": lines("from celery import Celery", "", 'app = Celery("shop")'),
  "shop/urls.py": lines("from django.urls import include, path", "", "urlpatterns = [", '    path("orders/", include("orders.urls")),', "]"),
  "orders/__init__.py": "",
  "orders/urls.py": lines(
    "from django.urls import path",
    "",
    "from . import views",
    "",
    "urlpatterns = [",
    '    path("", views.order_list, name="order-list"),',
    '    path("<int:pk>/", views.OrderDetail.as_view(), name="order-detail"),',
    '    path("legacy/", views.missing_view),',
    "]",
  ),
  "orders/views.py": lines(
    "from django.views import View",
    "",
    "from .services import place_order",
    "",
    "",
    "def order_list(request):",
    "    return place_order(request)",
    "",
    "",
    "class OrderDetail(View):",
    "    def get(self, request, pk):",
    "        return pk",
    "",
    "    def post(self, request, pk):",
    "        return place_order(request)",
  ),
  "orders/services.py": lines(
    "from .signals import order_placed",
    "from .tasks import send_receipt",
    "",
    "",
    "def place_order(request):",
    "    send_receipt.delay(1)",
    "    order_placed.send(sender=None, order=1)",
    "    return 1",
  ),
  "orders/signals.py": lines("from django.dispatch import Signal", "", "order_placed = Signal()"),
  "orders/tasks.py": lines(
    "from celery import shared_task",
    "",
    "from shop.celery import app",
    "",
    "",
    "@shared_task",
    "def send_receipt(order_id):",
    "    return order_id",
    "",
    "",
    '@app.task(name="orders.tasks.cleanup")',
    "def cleanup():",
    "    return 0",
  ),
  "orders/models.py": lines("class Order:", "    pass"),
  "orders/management/__init__.py": "",
  "orders/management/commands/__init__.py": "",
  "orders/management/commands/close_orders.py": lines(
    "from django.core.management.base import BaseCommand",
    "",
    "",
    "class Command(BaseCommand):",
    "    def handle(self, *args, **options):",
    "        return None",
  ),
  "notify/__init__.py": "",
  "notify/handlers.py": lines(
    "from django.db.models.signals import post_save",
    "from django.dispatch import receiver",
    "",
    "from orders.models import Order",
    "from orders.signals import order_placed",
    "",
    "",
    "def audit(sender, **kwargs):",
    "    return sender",
    "",
    "",
    "post_save.connect(audit, sender=Order)",
    "",
    "",
    "@receiver(order_placed)",
    "def email_customer(sender, **kwargs):",
    "    return sender",
  ),
  "keylang/flows.md": lines(
    "# flow placeOrder",
    "",
    "- trigger orders.services.place_order",
    "  - step orders.tasks.send_receipt",
    "  - step notify.handlers.email_customer",
  ),
};

/** FastAPI: a router with a prefix mounted with another prefix, route decorators, `Depends`. */
export const FASTAPI: Record<string, string> = {
  "keylang.json": JSON.stringify({ languages: ["python"], module: "file", layers: { api: ["api/**"] } }),
  "pyproject.toml": lines("[project]", 'name = "api"', 'dependencies = ["fastapi>=0.110"]'),
  "api/__init__.py": "",
  "api/db.py": lines("def get_db():", "    return None", "", "", "def verify_token():", "    return True"),
  "api/routers/__init__.py": "",
  "api/routers/orders.py": lines(
    "from fastapi import APIRouter, Depends",
    "",
    "from ..db import get_db, verify_token",
    "",
    'router = APIRouter(prefix="/orders")',
    "",
    "",
    '@router.get("/{order_id}")',
    "def read_order(order_id: int, db=Depends(get_db)):",
    "    return load(order_id)",
    "",
    "",
    '@router.post("/", dependencies=[Depends(verify_token)])',
    "def create_order():",
    "    return load(0)",
    "",
    "",
    "@router.websocket(\"/live\")",
    "def live():",
    "    return None",
    "",
    "",
    "def load(order_id):",
    "    return order_id",
  ),
  "api/main.py": lines(
    "from fastapi import FastAPI",
    "",
    "from .routers import orders",
    "",
    "app = FastAPI()",
    'app.include_router(orders.router, prefix="/api")',
    "",
    "",
    '@app.get("/health")',
    "def health():",
    '    return "ok"',
    "",
    "",
    "@cached",
    "def unknown():",
    "    return 1",
    "",
    "",
    "def cached(fn):",
    "    return fn",
  ),
};

/** Flask: an app route with methods and a blueprint with a prefix, registered with another. */
export const FLASK: Record<string, string> = {
  "keylang.json": JSON.stringify({ languages: ["python"], module: "file", layers: { web: ["web/**"] } }),
  "requirements.txt": lines("flask==3.0"),
  "web/__init__.py": "",
  "web/app.py": lines(
    "from flask import Flask",
    "",
    "from .orders import bp",
    "",
    "app = Flask(__name__)",
    'app.register_blueprint(bp, url_prefix="/shop")',
    "",
    "",
    '@app.route("/login", methods=["GET", "POST"])',
    "def login():",
    '    return "ok"',
  ),
  "web/orders.py": lines(
    "from flask import Blueprint",
    "",
    'bp = Blueprint("orders", __name__, url_prefix="/orders")',
    "",
    "",
    '@bp.route("/<int:order_id>")',
    "def show(order_id):",
    "    return str(order_id)",
    "",
    "",
    '@bp.post("/")',
    "def create():",
    '    return "created"',
  ),
};
