const {tui,mn}=TuiFrame("TUI · flow checkout — жолоб і помилка e2e",1380,3300,[["map/application.md",0],["flows/checkout.md",1,"✗"],["rules.md",0,"✗"],["keylang.toml",0]],"NORMAL","$accent",[[" ✗ 1 ","$fail"],[" ◌ 1 ","$warn"],["  flow checkout ",C.sig],["  13:7",C.cm]],[["t","запустити e2e"],["Enter","тест / код"],["]e","наступна"],["Space","згорнути"],["?","клавіші"]])
const ed=Box(mn,"flows/checkout.md · написано вручну",{width:"fill_container",height:"fill_container",pad:[12,8,8,4]})
Ln(ed,"1",null,[["# flow checkout",C.h,{fontWeight:"700"}]])
Ln(ed,"2",null,[["Покупець оформлює кошик у терміналі.",C.tx]])
Ln(ed,"3",null,[" "])
Ln(ed,"4",null,[Bl(),Kw("kind "),["business","$l-domain"]])
Ln(ed,"5","ok",[Bl(),Kw("trigger "),Id("presentation.terminal.checkout")])
Ln(ed,"6","ok",[Bl(),Kw("step "),Id("application.purchase.buy")])
Ln(ed,"7","ok",["  ",Bl(),Kw("reads "),Id("infrastructure.products.find")])
Ln(ed,"8","ok",["  ",Bl(),Kw("step "),Id("domain.orderAggregate.create")])
Ln(ed,"9","ok",["  ",Bl(),Kw("step "),Id("infrastructure.orderStore.save")])
Ln(ed,"10","unv",["  ",Bl(),Kw("emits "),["event order.created",C.tx]])
Banner(ed,"$warn","#D2992214",[[["◌ trace  ","$warn",{fontWeight:"700"}],["подію не записано під час e2e: статично виклик є, але в рантаймі не спрацював",C.sig]]])
Ln(ed,"11","ok",[Bl(),Kw("invariant "),["total = сума(price × qty) по позиціях",C.tx]])
Ln(ed,"12","ok",["  ",Bl(),Kw("test "),Pa("tests/e2e/checkout.e2e.ts"),[" \"computes total\"",C.sig]])
Ln(ed,"13","fail",[Bl(),Kw("when "),["товару немає на складі",C.tx]],{cur:1})
Ln(ed,"14",null,["  ",Bl(),Kw("then "),Id("application.purchase.OutOfStock")])
Ln(ed,"15","fail",["  ",Bl(),Kw("test "),Pa("tests/e2e/checkout.e2e.ts"),[" \"rejects out of stock\"",C.sig]])
const bn=Banner(ed,"$fail","#F8514914",[[["✗ e2e  ","$fail",{fontWeight:"700"}],["expected OutOfStock, got Order { id: \"o-17\", total: 0 }",C.h]],[["       at ",C.cm],Pa("tests/e2e/checkout.e2e.ts:41")],[["       trace ",C.cm],["buy → create → save",C.tx],["   products.find не викликано","$fail"]]])
const kk=F(bn,{name:"kpad",padding:[6,0,2,0]});Keys(kk,[["Enter","відкрити тест"],["t","перезапустити"],["Alt+Enter","до application.purchase.buy"]])
const rc=F(mn,{name:"Right column",width:300,height:"fill_container",layout:"vertical",gap:14})
const vb=Box(rc,"Перевірка",{width:"fill_container",pad:[12,8,8,8]})
Rows(vb,[[["статично  ",C.sig],["6/6 ","$ok",{fontWeight:"700"}],["✓","$ok"]],[["e2e       ",C.sig],["1/2 ","$fail",{fontWeight:"700"}],["✗","$fail"]],[["trace     ",C.sig],["5/6 ","$warn",{fontWeight:"700"}],["◌","$warn"]],[[" ",C.cm]],[["останній запуск 12 с тому",C.cm]]])
const nv=Box(rc,"Потоки",{width:"fill_container",height:"fill_container",pad:[12,8,8,8]})
Rows(nv,[[["BUSINESS",C.cm,{fontWeight:"700"}]],{s:[["  checkout      ",C.h,{fontWeight:"700"}],["✗ 1","$fail"]],sel:1},[["  cancel-order  ",C.tx],["✓","$ok"]],[[" ",C.cm]],[["TECHNICAL",C.cm,{fontWeight:"700"}]],[["  http-retry    ",C.tx],["◌ 2","$warn"]],[["  config-reload ",C.tx],["✓","$ok"]],[[" ",C.cm]],[["OUTLINE",C.cm,{fontWeight:"700"}]],[["  trigger",C.sig]],[["  steps · 6",C.sig]],[["  invariant · 1",C.sig]],[["  when · 1      ",C.sig],["✗","$fail"]]])
Update(tui,{placeholder:false})
Get(tui,(n,c)=>c.problems&&n.name!=="title"&&Print(n.name,"|",c.parentCtx&&c.parentCtx.node.name,"|",c.problems))
Export([tui],"png","/tmp/claude-1000/-home-kosmodev-pet-project-kosmo-lang-ai/4723d380-7591-4195-864a-ac659da5eac8/scratchpad/pen/exp",{scale:1})
