const {tui,mn}=TuiFrame("TUI · draft hybrid — злиття algo × LLM",0,4200,[["map/application.md",0],["flows/checkout.md · draft",1,"3"],["rules.md",0,"✗"]],"MERGE","$warn",[["  3 на рев'ю ","$warn"],["  1 відхилено ",C.cm],["  hybrid · claude-sonnet-5 · 31k ток.",C.sig]],[["a","прийняти"],["r","відхилити"],["]c","наступний"],["A","всі ="],["w","записати"],["Esc","скасувати"]])
const ed=Box(mn,"keylang draft flow checkout --mode hybrid",{width:"fill_container",height:"fill_container",pad:[12,8,8,4],tc:"$warn"})
Ln(ed,"1",null,[["# flow checkout",C.h,{fontWeight:"700"}]])
Ln(ed,"2","agree",[Bl(),Kw("trigger "),Id("presentation.terminal.checkout")])
Ln(ed,"3","agree",[Bl(),Kw("step "),Id("application.purchase.buy")])
Ln(ed,"4","algo",["  ",Bl(),Kw("reads "),Id("infrastructure.products.find"),["   algo-only",C.cm]])
Ln(ed,"5","llm",["  ",Bl(),Kw("step "),Id("infrastructure.payments.charge"),[" <!-- keylang:llm status=llm-only -->",C.cm]],{cur:1})
Banner(ed,"$warn","#D2992214",[[["+? LLM  ","$warn",{fontWeight:"700"}],["«оплата картою». У графі викликів немає — ймовірно, через DI.",C.sig]],[["       ",C.cm],["підтвердити: додай ",C.cm],["wire",C.kw],[" або підключи SCIP",C.cm]]])
Ln(ed,"6","agree",["  ",Bl(),Kw("step "),Id("domain.orderAggregate.create")])
Ln(ed,"7","agree",["  ",Bl(),Kw("step "),Id("infrastructure.orderStore.save")])
Ln(ed,"8","conf",[["<<<<<<< algo",C.cm]])
Ln(ed,"9","conf",["  ",Bl(),Kw("emits "),["event order.created",C.tx],["      після save","$accent"]])
Ln(ed,"10","conf",[["=======",C.cm]])
Ln(ed,"11","conf",["  ",Bl(),Kw("emits "),["event order.created",C.tx],["      перед save","$warn"]])
Ln(ed,"12","conf",[[">>>>>>> llm",C.cm]])
Ln(ed,"13","llm",[Bl(),Kw("when "),["кошик порожній",C.tx]])
Ln(ed,"14","llm",["  ",Bl(),Kw("then "),Id("application.purchase.EmptyCart")])
Ln(ed,"15","llm",["  ",Bl(),Kw("test "),["потрібен e2e — ще не існує",C.cm]])
Ln(ed,"16","fail",["  ",["- step billing.invoice.create",C.n,{strikethrough:true}],["   K001 немає такого ID — відхилено автоматично","$fail"]])
const rc=F(mn,{name:"Right column",width:300,height:"fill_container",layout:"vertical",gap:14})
const sb=Box(rc,"Звіряння",{width:"fill_container",pad:[12,8,8,8]})
Rows(sb,[[["=  ","$ok",{fontWeight:"700"}],["agree       ",C.sig],["9","$ok",{fontWeight:"700"}]],[["=  ","$accent",{fontWeight:"700"}],["algo-only   ",C.sig],["1","$accent",{fontWeight:"700"}]],[["+? ","$warn",{fontWeight:"700"}],["llm-only    ",C.sig],["2","$warn",{fontWeight:"700"}]],[["!  ","$fail",{fontWeight:"700"}],["conflict    ",C.sig],["1","$fail",{fontWeight:"700"}]],[["✗  ",C.n,{fontWeight:"700"}],["відхилено   ",C.sig],["1",C.n,{fontWeight:"700"}]]])
const hb=Box(rc,"Режим",{width:"fill_container",pad:[12,8,8,8]})
Rows(hb,[[["  algo   ",C.sig],["граф з AST",C.cm]],[["  llm    ",C.sig],["зміст, наміри",C.cm]],{s:[["▸ hybrid ",C.h,{fontWeight:"700"}],["обидва + звіряння",C.cm]],sel:1},[[" ",C.cm]],[["m",C.h],[" змінити режим",C.cm]]])
const lg=Box(rc,"Легенда",{width:"fill_container",height:"fill_container",pad:[12,8,8,8]})
Rows(lg,[[["=  ","$ok"],["факт і зміст збіглися",C.cm]],[["+? ","$warn"],["лише LLM → рев'ю",C.cm]],[["!  ","$fail"],["суперечність → вибір",C.cm]],[[" ",C.cm]],[["CI не приймає +? автоматично",C.cm]]])
Update(tui,{placeholder:false})
Get(tui,(n,c)=>c.problems&&n.name!=="title"&&Print(n.name,"|",c.parentCtx&&c.parentCtx.node.name,"|",c.problems))
Export([tui],"png","/tmp/claude-1000/-home-kosmodev-pet-project-kosmo-lang-ai/4723d380-7591-4195-864a-ac659da5eac8/scratchpad/pen/exp",{scale:1})
