const {tui,mn}=TuiFrame("TUI · пояснення вузла (e)",1380,4200,[["map/application.md",1],["flows/checkout.md",0,"✗"],["rules.md",0,"✗"]],"EXPLAIN","$l-app",[["  application.purchase.buy ",C.sig],["  LLM · актуально",C.cm]],[["e","закрити"],["Tab","short / full"],["R","перегенерувати"],["Enter","перейти за ID"],["y","копіювати"]])
const ed=Box(mn,"map/application.md · згенеровано",{width:"fill_container",height:"fill_container",pad:[12,8,8,4]})
Ln(ed,"2",null,[["# application",C.h,{fontWeight:"700"}]])
Ln(ed,"3",null,[["Сервіси бізнес-логіки.",C.tx]])
Ln(ed,"4",null,[" "])
Ln(ed,"5","ok",[Bl(),Kw("module "),["[",C.b],["purchase",C.h,{fontWeight:"700"}],["](",C.b],Pa("src/app/purchase.ts#L1"),[")",C.b]])
Ln(ed,"6",null,["  ",Bl(),["order    ",C.sig],Id("domain.orderAggregate")])
Ln(ed,"7",null,["  ",Bl(),["catalog  ",C.sig],Id("infrastructure.products")])
Ln(ed,"8",null,["  ",Bl(),["orders   ",C.sig],Id("infrastructure.orderStore")])
Ln(ed,"9","ok",["  ",Bl(),Kw("fn "),["[",C.b],["buy","$l-app",{fontWeight:"700",underline:true}],["](",C.b],Pa("src/app/purchase.ts#L12"),[") ",C.b],["(cart: Cart) → Promise<Order>",C.sig]],{cur:1})
Ln(ed,"10","ok",["    ",Bl(),Kw("calls "),Id("domain.orderAggregate.create"),[", ",C.b],Id("infrastructure.orderStore.save")])
Ln(ed,"11","ok",["  ",Bl(),Kw("fn "),["[",C.b],["cancel","$l-app",{fontWeight:"700"}],["](",C.b],Pa("src/app/purchase.ts#L30"),[") ",C.b],["(id: OrderId) → Promise<void>",C.sig]])
Ln(ed,"12","ok",["    ",Bl(),Kw("calls "),Id("infrastructure.orderStore.remove")])
const ex=Box(mn,"Пояснення · fn application.purchase.buy",{width:500,height:"fill_container",pad:[14,14,10,14],gap:10,tc:"$l-app",stroke:"#3DD6B566"})
const tb=F(ex,{name:"mode tabs",gap:0,alignItems:"center"});for(const [t,a] of [["short",0],["full",1]]){const x=F(tb,{name:"t "+t,padding:[0,8],fill:a?C.sel:undefined});Sp(x,t,a?C.h:C.cm,{fontWeight:a?"700":"400"})}Sp(tb,"   мова: uk",C.cm)
function P(t){return Insert(ex,{type:"text",name:"para",content:t,fontFamily:"$font-code",fontSize:FS,lineHeight:1.55,fill:C.tx,textGrowth:"fixed-width",width:"fill_container"})}
function H(t){Sp(ex,t,C.cm,{fontWeight:"700"})}
H("ЩО РОБИТЬ")
P("Оформлює покупку: з кошика створює замовлення, рахує суму й зберігає його. Повертає збережене замовлення.")
H("ЯК")
const st=F(ex,{name:"steps",width:"fill_container",layout:"vertical",gap:2})
for(const r of [[["1. ",C.cm],["бере товари через ",C.tx],Id("infrastructure.products")],[["2. ",C.cm],["будує замовлення — ",C.tx],Id("domain.orderAggregate.create")],[["3. ",C.cm],["зберігає — ",C.tx],Id("infrastructure.orderStore.save")]]){const x=F(st,{name:"step",alignItems:"center"});for(const s2 of r)Sp(x,s2[0],s2[1],s2[2])}
H("КРАЙНІ ВИПАДКИ")
P("Наявність товару на складі не перевіряється: порожній склад дає замовлення з total = 0. Саме це ловить падіння e2e у flow checkout.")
const lk=F(ex,{name:"link",alignItems:"center"});Sp(lk,"→ ",C.cm);Sp(lk,"flow checkout",C.tx,{underline:true});Sp(lk,"  ✗ when товару немає на складі","$fail")
F(ex,{name:"sp",width:"fill_container",height:"fill_container"})
Sp(ex,"─".repeat(50),"#3A4452")
const ft=F(ex,{name:"footer",layout:"vertical",gap:2})
for(const r of [[["джерела  ",C.cm],["код fn · 3 залежності · 1 потік",C.sig]],[["модель   ",C.cm],["claude-sonnet-5 · 2.1k ток.",C.sig]],[["хеш      ",C.cm],["3f2a91 ",C.sig],["✓ актуально","$ok"]]]){const x=F(ft,{name:"meta",alignItems:"center"});for(const s2 of r)Sp(x,s2[0],s2[1],s2[2])}
Update(tui,{placeholder:false})
Get(tui,(n,c)=>c.problems&&n.name!=="title"&&Print(n.name,"|",c.parentCtx&&c.parentCtx.node.name,"|",c.problems))
Export([tui],"png","/tmp/claude-1000/-home-kosmodev-pet-project-kosmo-lang-ai/4723d380-7591-4195-864a-ac659da5eac8/scratchpad/pen/exp",{scale:1})
