const comp=Get(n=>n.name==="TUI · map (component)"?n.id:undefined)[0]
const a=Insert(document,{type:"frame",name:"Варіант A · keylang у терміналі",x:0,y:5100,layout:"vertical",cornerRadius:10,clip:true,fill:"#1E1E1E",stroke:"#3A3A3A",strokeWidth:1,effect:{type:"shadow",offset:{x:0,y:16},blur:40,color:"#00000090"},placeholder:true})
const tb=F(a,{name:"Title bar",width:"fill_container",height:38,padding:[0,12],alignItems:"center",fill:"#2B2B2B"})
const l=F(tb,{name:"left",width:120,gap:6,alignItems:"center"});Ic(l,"plus",14,"#9A9A9A")
const c=F(tb,{name:"center",width:"fill_container",justifyContent:"center",gap:8,alignItems:"center"});Ic(c,"square-terminal",14,"#BDBDBD");T(c,"keylang — ~/pet_project/shop-example",{fill:"#DADADA",fontWeight:"600"});T(c,"160×45",{fill:"#8A8A8A",fontSize:12})
const r=F(tb,{name:"right",width:120,gap:14,justifyContent:"end",alignItems:"center"});for(const i of ["minus","square","x"])Ic(r,i,13,"#BDBDBD")
const cm=F(a,{name:"prompt",width:"fill_container",padding:[6,12],fill:"#0D1015"});Sp(cm,"$ ",C.cm);Sp(cm,"keylang",C.h);Sp(cm," .",C.sig)
Insert(a,{type:"ref",ref:comp,name:"TUI instance"})
Update(a,{placeholder:false})
const b=Insert(document,{type:"frame",name:"Варіант B · keylang web у браузері",x:1380,y:5100,layout:"vertical",cornerRadius:10,clip:true,fill:"#202124",stroke:"#3A3A3A",strokeWidth:1,effect:{type:"shadow",offset:{x:0,y:16},blur:40,color:"#00000090"},placeholder:true})
const ts=F(b,{name:"Tab strip",width:"fill_container",height:38,padding:[6,10,0,10],gap:6,alignItems:"end",fill:"#1A1B1E"})
const dots=F(ts,{name:"dots",gap:7,padding:[0,8,12,2],alignItems:"center"});for(const col of ["#FF5F57","#FEBC2E","#28C840"])Insert(dots,{type:"ellipse",name:"dot",width:12,height:12,fill:col})
const tab=F(ts,{name:"Tab",width:260,padding:[8,12],gap:8,alignItems:"center",cornerRadius:[8,8,0,0],fill:"#2B2C30"});Ic(tab,"square-terminal",13,"#8AA4FF");T(tab,"keylang · shop-example",{fill:"#E8EAED",fontSize:12.5});F(tab,{name:"sp",width:"fill_container",height:1});Ic(tab,"x",12,"#9AA0A6")
Ic(ts,"plus",14,"#9AA0A6")
const ab=F(b,{name:"Address bar",width:"fill_container",padding:[7,12],gap:12,alignItems:"center",fill:"#2B2C30"})
for(const i of ["arrow-left","arrow-right","rotate-cw"])Ic(ab,i,15,"#9AA0A6")
const url=F(ab,{name:"URL",width:"fill_container",padding:[6,14],gap:8,alignItems:"center",cornerRadius:16,fill:"#1A1B1E"});Ic(url,"info",13,"#9AA0A6");T(url,"localhost:7070",{fill:"#E8EAED"});T(url,"/?repo=shop-example",{fill:"#9AA0A6"})
const wsb=F(ab,{name:"ws",padding:[3,8],gap:6,alignItems:"center",cornerRadius:10,stroke:"#3FB95088",strokeWidth:1});Dot(wsb,"$ok",7);T(wsb,"WS · PTY",{fontSize:11.5,fill:"#9AA0A6"})
Insert(b,{type:"ref",ref:comp,name:"TUI instance"})
Update(b,{placeholder:false})
const n=Insert(document,{type:"frame",name:"Примітка · два запуски",x:0,y:6080,width:2640,layout:"vertical",gap:6,padding:[16,20],cornerRadius:8,fill:"$panel",stroke:"$border",strokeWidth:1})
T(n,"Той самий TUI, два запуски",{fontSize:16,fontWeight:"700"})
T(n,"A: keylang — ratatui + crossterm у будь-якому терміналі. B: keylang web — той самий процес у PTY, екран іде в xterm.js через WebSocket. Окремого фронтенду немає: клавіші, мишка, hover і вигляд однакові. Перехід у код: $EDITOR / code -g (A) або OSC 8 vscode://… (B).",{fill:"$text-2",textGrowth:"fixed-width",width:"fill_container",lineHeight:1.5})
Get(a,(x,cc)=>cc.problems&&Print(x.name,"|",cc.problems));Get(b,(x,cc)=>cc.problems&&Print(x.name,"|",cc.problems))
Export([a,b],"png","/tmp/claude-1000/-home-kosmodev-pet-project-kosmo-lang-ai/4723d380-7591-4195-864a-ac659da5eac8/scratchpad/pen/exp",{scale:1})
