const s0=Get(n=>n.name==="TUI · редактор — автодоповнення з індексу + ghost агента"?n.id:undefined)[0]
Get(s0,n=>{if(n.type==="text"&&typeof n.content==="string"){const m={"(order: Order) → Promise<void>":"(order) → void","(id: OrderId) → Promise<void>":"(id) → void","(id) → Order | undefined":"(id) → Order?"};if(m[n.content])Update(n.id,{content:m[n.content]})}})
const {tui,mn}=TuiFrame("TUI · агент — співавторство, контекст, голос",1380,6300,[["flows/refund.md ●",1],["src/infra/payments.ts",0]],"AGENT","$l-infra",[["  2 шматки на рев'ю ","$warn"],["  anthropic:claude-sonnet-5",C.sig],["  контекст 5.3k",C.cm]],[["a","прийняти"],["r","відхилити"],["e","правити"],["@","контекст"],["Ctrl+R","голос"],["Esc","назад"]])
const ed=Box(mn,"flows/refund.md · пропозиція агента",{width:"fill_container",height:"fill_container",pad:[12,8,8,4],tc:"$l-infra"})
Ln(ed,"1",null,[["# flow refund",C.h,{fontWeight:"700"}]])
Ln(ed,"2",null,[["Повернення коштів за скасоване замовлення тим самим способом оплати.",C.tx]])
Ln(ed,"3",null,[" "])
Ln(ed,"4",null,[Bl(),Kw("kind "),["business","$l-domain"]])
Ln(ed,"5","unv",[Bl(),Kw("trigger "),["presentation.api.refund","$l-pres"]])
Ln(ed,"6","ok",[Bl(),Kw("step "),Id("application.purchase.cancel")])
Ln(ed,"7","ok",["  ",Bl(),Kw("reads "),Id("infrastructure.orderStore.find")])
Ln(ed,"8","ok",["  ",Bl(),Kw("step "),Id("infrastructure.orderStore.remove")])
const h1=F(ed,{name:"hunk 1",width:"fill_container",layout:"vertical",fill:"#3FB95012",stroke:"$ok",strokeWidth:{left:2}})
Ln(h1,"9","add",["  ",Bl(),Kw("step "),["infrastructure.payments.refund","$l-infra"],["   новий · spec-to-code",GH]],{cur:1})
Ln(h1,"10","add",["    ",Bl(),Kw("reads "),Id("infrastructure.orderStore.find")])
Ln(h1,"11","add",["  ",Bl(),Kw("emits "),["event order.refunded",C.tx]])
const hk=F(h1,{name:"hk",padding:[2,0,4,62]});Keys(hk,[["a","прийняти шматок 1/2"],["r","відхилити"],["e","правити вручну"]])
const h2=F(ed,{name:"hunk 2",width:"fill_container",layout:"vertical",fill:"#3FB95012",stroke:"$ok",strokeWidth:{left:2}})
Ln(h2,"12","add",[Bl(),Kw("when "),["повернення пізніше 14 днів",C.tx]])
Ln(h2,"13","add",["  ",Bl(),Kw("then "),["application.purchase.RefundExpired","$l-app"]])
Ln(h2,"14","add",["  ",Bl(),Kw("test "),["tests/e2e/refund.e2e.ts","$ok"],[" \"expired refund\"   + заготовка e2e",GH]])
const rc=Box(mn,"Агент",{width:460,height:"fill_container",pad:[12,10,8,10],gap:10,tc:"$l-infra"})
Sp(rc,"КОНТЕКСТ · 5.3k токенів",C.cm,{fontWeight:"700"})
const cx=F(rc,{name:"context",width:"fill_container",layout:"vertical",gap:1})
for(const [k,t,n,pin] of [["буфер","flows/refund.md","0.4k",1],["вузол","application.purchase","0.9k",1],["вузол","infrastructure.orderStore","0.6k",0],["потік","flows/cancel-order.md","0.7k",0],["правила","rules.md","0.3k",0],["код","src/app/purchase.ts:30-52","1.1k",0],["e2e","tests/e2e/checkout.e2e.ts","1.3k",0]]){const r=F(cx,{name:"ctx "+t,width:"fill_container",padding:[0,4],alignItems:"center"});Sp(r,pin?"● ":"○ ",pin?"$accent":C.cm);Sp(r,k.padEnd(8," "),C.cm);Sp(r,t,t.includes(".")&&!t.includes("/")?idCol(t):C.tx);F(r,{name:"sp",width:"fill_container",height:1});Sp(r,n,C.sig)}
const ca=F(cx,{name:"ctx add",padding:[2,4]});Sp(ca,"@",C.h,{fontWeight:"700"});Sp(ca," додати вузол · ",C.cm);Sp(ca,"x",C.h);Sp(ca," прибрати · ",C.cm);Sp(ca,"●",C.accent||"#8AA4FF");Sp(ca," закріплено",C.cm)
Sp(rc,"─".repeat(48),"#3A4452")
function msg(who,col,t){const m=F(rc,{name:"msg "+who,width:"fill_container",layout:"vertical",gap:2});Sp(m,who,col,{fontWeight:"700"});Insert(m,{type:"text",name:"body",content:t,fontFamily:"$font-code",fontSize:FS,lineHeight:1.5,fill:C.tx,textGrowth:"fixed-width",width:"fill_container"});return m}
const u=msg("ти · 🎙 голос","$accent","додай повернення коштів через той самий спосіб оплати, і щоб не можна було повернути пізніше 14 днів")
msg("агент","$l-infra","Додав крок infrastructure.payments.refund (його ще немає в коді — можу створити через spec-to-code) і гілку when для 14 днів із заготовкою e2e. Решту взяв з cancel-order.")
F(rc,{name:"sp",width:"fill_container",height:"fill_container"})
const ib=F(rc,{name:"input",width:"fill_container",layout:"vertical",gap:4,padding:[8,10],stroke:"$fail",strokeWidth:1,fill:"#F851490D"})
const r1=F(ib,{name:"rec",width:"fill_container",alignItems:"center"});Sp(r1,"● REC 00:06  ","$fail",{fontWeight:"700"});Sp(r1,"▁▂▅▇▆▃▂▅▇▅▂▁","$fail");F(r1,{name:"sp",width:"fill_container",height:1});Sp(r1,"local · whisper small",C.cm)
Sp(ib,"а ще логуй кожне повернення в аудит…",C.sig,{fontStyle:"italic"})
const r2=F(ib,{name:"opts",width:"fill_container",alignItems:"center"});Keys(r2,[["Ctrl+R","стоп"],["Tab","local ⇄ openrouter"],["Enter","надіслати"]])
Update(tui,{placeholder:false})
Get(tui,(n,c)=>c.problems&&n.name!=="title"&&Print(n.name,"|",c.parentCtx&&c.parentCtx.node.name,"|",c.problems))
Export([s0,tui],"png","/tmp/claude-1000/-home-kosmodev-pet-project-kosmo-lang-ai/4723d380-7591-4195-864a-ac659da5eac8/scratchpad/pen/exp",{scale:1})
