const LC={domain:"$l-domain",application:"$l-app",infrastructure:"$l-infra",presentation:"$l-pres"}
const layerOf=id=>id.split(".")[0]
function F(p,o){return Insert(p,{type:"frame",...o})}
function T(p,c,o){return Insert(p,{type:"text",name:o&&o.name||c.slice(0,24),content:c,fontFamily:"$font-ui",fontSize:13,fill:"$text",...o})}
function M(p,c,o){return T(p,c,{fontFamily:"$font-code",fontSize:12.5,...o})}
function Ic(p,icon,s,fill){return Insert(p,{type:"icon",name:"icon "+icon,library:"lucide",icon,width:s||14,height:s||14,fill:fill||"$text-2"})}
function Dot(p,col,s){return Insert(p,{type:"ellipse",name:"dot",width:s||8,height:s||8,fill:col})}
function Kbd(p,k){const f=F(p,{name:"kbd "+k,padding:[2,6],cornerRadius:4,fill:"$panel-2",stroke:"$border",strokeWidth:1});M(f,k,{fontSize:11,fill:"$text-2"});return f}
function IdTok(p,id,o){const f=F(p,{name:"id "+id,padding:[3,8],gap:6,alignItems:"center",cornerRadius:5,fill:"$panel-2",...o});Dot(f,LC[layerOf(id)]||"$text-3",6);M(f,id,{name:"id text",fill:"$text"});return f}
const ST={ok:["$ok","circle-check","ok"],fail:["$fail","circle-x","fail"],unv:["$warn","circle-dashed","unverified"]}
function Badge(p,s,label){const [c,i,l]=ST[s];const f=F(p,{name:"badge "+s,padding:[2,8],gap:5,alignItems:"center",cornerRadius:10,stroke:c,strokeWidth:1});Ic(f,i,12,c);T(f,label||l,{fontSize:11.5,fill:c,fontWeight:"500"});return f}
function Btn(p,label,o){const pr=o&&o.primary;const f=F(p,{name:"btn "+label,padding:[7,14],gap:6,alignItems:"center",cornerRadius:6,fill:pr?"$accent":"$panel-2",stroke:pr?undefined:"$border",strokeWidth:pr?0:1});if(o&&o.icon)Ic(f,o.icon,14,pr?"#0D1015":"$text-2");T(f,label,{fontWeight:"600",fill:pr?"#0D1015":"$text"});return f}
function Screen(name,x,y,h){return Insert(document,{type:"frame",name,x,y,width:1440,height:h||900,layout:"vertical",fill:"$bg",clip:true,placeholder:true})}
function TopBar(s,active){const b=F(s,{name:"Top bar",width:"fill_container",height:52,padding:[0,16],gap:20,alignItems:"center",fill:"$panel",stroke:"$border",strokeWidth:{bottom:1}});
const lg=F(b,{name:"Brand",gap:10,alignItems:"center"});M(lg,"keylang",{fontSize:16,fontWeight:"700",fill:"$accent"});const rp=F(lg,{name:"Repo",padding:[4,8],gap:6,alignItems:"center",cornerRadius:6,fill:"$panel-2"});Ic(rp,"git-branch",13);T(rp,"shop-example",{fontWeight:"500"});T(rp,"main",{fill:"$text-3",fontSize:12});Ic(rp,"chevron-down",13);
const tabs=F(b,{name:"Tabs",gap:4,alignItems:"center"});for(const [k,l,i] of [["map","Карта","list-tree"],["flows","Потоки","workflow"],["rules","Правила","shield-check"],["checks","Перевірки","activity"],["settings","Налаштування","settings"]]){const a=k===active;const t=F(tabs,{name:"tab "+l,padding:[6,10],gap:6,alignItems:"center",cornerRadius:6,fill:a?"$accent-bg":undefined});Ic(t,i,14,a?"$accent":"$text-2");T(t,l,{fill:a?"$accent":"$text-2",fontWeight:a?"600":"500"})}
F(b,{name:"Spacer",width:"fill_container",height:1});
const sr=F(b,{name:"Go to ID",width:320,padding:[6,10],gap:8,alignItems:"center",cornerRadius:6,fill:"$bg",stroke:"$border",strokeWidth:1});Ic(sr,"search",14,"$text-3");T(sr,"Перейти до ID, файлу, потоку…",{fill:"$text-3",name:"placeholder"});F(sr,{name:"sp",width:"fill_container",height:1});Kbd(sr,"Ctrl K");
const st=F(b,{name:"Check summary",gap:8,alignItems:"center"});Badge(st,"fail","2");Badge(st,"unv","5");Btn(b,"Перевірити",{primary:true,icon:"play"});return b}
function Tree(p,rows){for(const r of rows){const sel=r.sel;const row=F(p,{name:"row "+r.l,width:"fill_container",padding:[4,10,4,10+(r.d||0)*16],gap:6,alignItems:"center",cornerRadius:5,fill:sel?"$accent-bg":undefined});
if(r.ch!==undefined)Ic(row,r.ch?"chevron-down":"chevron-right",12,"$text-3");else F(row,{name:"indent",width:12,height:12});
if(r.layer)Dot(row,LC[r.layer],8);else if(r.icon)Ic(row,r.icon,13,r.ic||"$text-3");
(r.mono===false?T:M)(row,r.l,{fill:sel?"$accent":r.dim?"$text-2":"$text",fontWeight:r.layer?"600":"400",fontSize:r.layer?12.5:12});
if(r.meta){F(row,{name:"sp",width:"fill_container",height:1});T(row,r.meta,{fontSize:11,fill:"$text-3"})}
if(r.badge){F(row,{name:"sp",width:"fill_container",height:1});Badge(row,r.badge,r.bl)}}}
function RightPanel(p,rows,tab){const r=F(p,{name:"Right panel · Navigation",width:320,height:"fill_container",layout:"vertical",fill:"$panel",stroke:"$border",strokeWidth:{left:1}});
const h=F(r,{name:"Panel tabs",width:"fill_container",padding:[0,12],gap:16,height:40,alignItems:"center",stroke:"$border",strokeWidth:{bottom:1}});for(const l of ["Навігація","Outline","Зв'язки"]){const a=l===(tab||"Навігація");const t=F(h,{name:"ptab "+l,height:"fill_container",alignItems:"center",stroke:a?"$accent":undefined,strokeWidth:a?{bottom:2}:0});T(t,l,{fontSize:12.5,fill:a?"$text":"$text-3",fontWeight:a?"600":"500"})}
const fl=F(r,{name:"Filter wrap",width:"fill_container",padding:[10,12]});const fi=F(fl,{name:"Filter",width:"fill_container",padding:[6,10],gap:8,alignItems:"center",cornerRadius:6,fill:"$bg",stroke:"$border",strokeWidth:1});Ic(fi,"list-filter",13,"$text-3");T(fi,"Фільтр вузлів…",{fill:"$text-3",fontSize:12.5});
const body=F(r,{name:"Tree",width:"fill_container",height:"fill_container",layout:"vertical",padding:[0,6],gap:1});Tree(body,rows);return r}
function Section(p,l){const s=F(p,{name:"sec "+l,width:"fill_container",padding:[14,10,6,10]});T(s,l.toUpperCase(),{fontSize:10.5,letterSpacing:0.8,fill:"$text-3",fontWeight:"600"});return s}
function StatusBar(s,mid){const b=F(s,{name:"Status bar",width:"fill_container",height:28,padding:[0,14],gap:16,alignItems:"center",fill:"$panel",stroke:"$border",strokeWidth:{top:1}});const l=F(b,{name:"lsp",gap:6,alignItems:"center"});Dot(l,"$ok",7);T(l,"keylang lsp · індекс 142 вузли · 0.3 с",{fontSize:11.5,fill:"$text-2"});F(b,{name:"sp",width:"fill_container",height:1});if(mid){const m=F(b,{name:"mode",gap:6,alignItems:"center"});Kbd(m,"Ctrl");T(m,mid,{fontSize:11.5,fill:"$accent"})}F(b,{name:"sp2",width:"fill_container",height:1});T(b,"Rust · TypeScript · tree-sitter",{fontSize:11.5,fill:"$text-3"});return b}
const NAV=[{l:"domain",layer:"domain",ch:true},{l:"orderAggregate",d:1,icon:"box",ch:false},{l:"infrastructure",layer:"infrastructure",ch:true},{l:"config",d:1,icon:"box"},{l:"logger",d:1,icon:"box"},{l:"products",d:1,icon:"box"},{l:"orderStore",d:1,icon:"box",ch:true},{l:"save",d:2,icon:"square-function",dim:true},{l:"server",d:1,icon:"box"},{l:"application",layer:"application",ch:true},{l:"purchase",d:1,icon:"box",ch:true,sel:true},{l:"buy",d:2,icon:"square-function",dim:true},{l:"cancel",d:2,icon:"square-function",dim:true},{l:"presentation",layer:"presentation",ch:false}]
const C={kw:"#FF7AB2",cm:"#6C7986",path:"#6BDFFF",sig:"#A8B1BD",tx:"#DDE3EA",b:"#6C7986",h:"#FFFFFF",n:"#4B5563",sel:"#243044"}
const FS=13,LH=1.5
function Sp(p,t,col,o){return Insert(p,{type:"text",name:"sp "+t.slice(0,16),content:t,fontFamily:"$font-code",fontSize:FS,lineHeight:LH,fill:col||C.tx,...o})}
function idCol(id){return LC[layerOf(id)]||C.tx}
function Ln(p,n,st,spans,o){const r=F(p,{name:"ln "+n,width:"fill_container",alignItems:"center",fill:o&&o.cur?C.sel:undefined});const g=F(r,{name:"gutter",width:44,justifyContent:"end",padding:[0,8,0,0]});Sp(g,n===""?" ":String(n),C.n);const s=F(r,{name:"st",width:18});if(st){const m={ok:["✓","$ok"],fail:["✗","$fail"],unv:["◌","$warn"],llm:["+?","$warn"],agree:["=","$ok"],conf:["!","$fail"],algo:["=","$accent"],add:["+","$ok"],del:["-","$fail"],gh:["✦","#56606C"]}[st];Sp(s,m[0],m[1],{fontWeight:"700"})}else Sp(s," ");const tx=F(r,{name:"text",gap:0,alignItems:"center"});for(const x of spans){if(typeof x==="string")Sp(tx,x);else Sp(tx,x[0],x[1],x[2])}return r}
function Box(p,title,o){o=o||{};const {pad,tc,...rest}=o;const b=F(p,{name:"box "+title,layout:"vertical",strokeWidth:1,...rest,stroke:rest.stroke||"#3A4452",padding:pad||[10,10,6,10]});const t=F(b,{name:"title",layoutPosition:"absolute",x:12,y:-10,padding:[0,4],fill:rest.fill||"$bg"});Sp(t,title,tc||C.sig,{fontWeight:"600"});return b}
function Kw(t){return [t,C.kw]} function Cm(t){return [t,C.cm]} function Id(t,o){return [t,idCol(t),o]} function Pa(t){return [t,C.path,{underline:true}]} function Bl(t){return [t||"- ",C.b]}
function TuiFrame(name,x,y,tabs,mode,mcol,st,hints){const tui=Insert(document,{type:"frame",name,x,y,width:1280,height:800,layout:"vertical",fill:"$bg",clip:true,placeholder:true});const tl=F(tui,{name:"Tab line",width:"fill_container",alignItems:"center",fill:"#10141A"});const br=F(tl,{name:"brand",padding:[4,10],fill:"$accent"});Sp(br,"keylang","#0D1015",{fontWeight:"700"});for(const [t,a,s2] of tabs){const x2=F(tl,{name:"tab "+t,padding:[4,12],gap:8,fill:a?C.sel:undefined,alignItems:"center"});Sp(x2,t,a?C.h:C.sig);if(s2)Sp(x2,s2,s2==="✗"?"$fail":"$warn")}F(tl,{name:"sp",width:"fill_container",height:1});const rp=F(tl,{name:"repo",padding:[4,12]});Sp(rp,"shop-example · main",C.cm);const mn=F(tui,{name:"Main",width:"fill_container",height:"fill_container",gap:8,padding:[14,8,8,8]});const sl=F(tui,{name:"Status line",width:"fill_container",alignItems:"center",fill:"#10141A"});const md=F(sl,{name:"mode",padding:[3,10],fill:mcol});Sp(md,mode,"#0D1015",{fontWeight:"700"});for(const [t,c2] of st)Sp(sl,t,c2);F(sl,{name:"sp",width:"fill_container",height:1});for(const [k,t] of hints){const g=F(sl,{name:"hint "+k,gap:5,padding:[3,8],alignItems:"center"});const kb=F(g,{name:"kb",padding:[0,5],fill:"#2A3340"});Sp(kb,k,C.h);Sp(g,t,C.sig)}return {tui,mn}}
function Banner(p,col,bg,lines){const b=F(p,{name:"inline banner",width:"fill_container",layout:"vertical",padding:[4,10,4,62],fill:bg,stroke:col,strokeWidth:{left:2}});for(const l of lines){const r=F(b,{name:"bl",alignItems:"center"});for(const s2 of l)Sp(r,s2[0],s2[1],s2[2])}return b}
function Keys(p,list){const hk=F(p,{name:"keys",gap:14,alignItems:"center"});for(const [k,t] of list){const g=F(hk,{name:"k "+k,gap:6,alignItems:"center"});const kb=F(g,{name:"kb",padding:[0,5],fill:"#3A4452"});Sp(kb,k,C.h);Sp(g,t,C.sig)}return hk}
function Rows(p,rows){for(const r of rows){const x=F(p,{name:"row",width:"fill_container",padding:[0,4],fill:r.sel?C.sel:undefined});for(const s2 of (r.s||r))Sp(x,s2[0],s2[1],s2[2])}}
const GH="#5A6573"
function Gh(t){return [t,GH,{fontStyle:"italic"}]}
function Menu(p,title,x,y,w,items,sel,o){const b=Box(p,title,{layoutPosition:"absolute",x,y,width:w,fill:"$panel-2",stroke:"#8AA4FF88",pad:[12,4,6,4],gap:0,tc:(o&&o.tc)||C.sig,effect:{type:"shadow",offset:{x:0,y:10},blur:28,color:"#000000A0"}});items.forEach((it,i)=>{const r=F(b,{name:"item",width:"fill_container",padding:[1,8],gap:0,alignItems:"center",fill:i===sel?C.sel:undefined,opacity:it.dis?0.5:1});for(const s2 of it.s)Sp(r,s2[0],s2[1],s2[2]);if(it.r){F(r,{name:"sp",width:"fill_container",height:1});for(const s2 of it.r)Sp(r,s2[0],s2[1],s2[2])}});return b}
